import { useFrappeGetDocList } from "frappe-react-sdk";
import React from "react";

const HistorySection = ({ task_id }) => {
  const versions_query = useFrappeGetDocList("Version", {
    filters: [
      ["ref_doctype", "=", "Task"],
      ["docname", "=", task_id],
    ],
    fields: ["*"],
    order_by: "creation desc",
    limit_page_length: 50,
  });
  console.log("versions_query", versions_query.data);
    const versions = versions_query?.data || [];

//   const versions = [
//     {
//       name: "0hm353em6d",
//       owner: "Administrator",
//       creation: "2026-01-30 19:29:12.612903",
//       modified: "2026-01-30 19:29:12.612903",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Working","Open"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "0psba4ou97",
//       owner: "Administrator",
//       creation: "2026-01-30 19:29:38.880205",
//       modified: "2026-01-30 19:29:38.880205",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Open","Working"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "0qa79heqht",
//       owner: "Administrator",
//       creation: "2026-01-30 19:29:40.208408",
//       modified: "2026-01-30 19:29:40.208408",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Working","Pending Review"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "0qpcngqm98",
//       owner: "Administrator",
//       creation: "2026-01-30 19:29:41.718830",
//       modified: "2026-01-30 19:29:41.718830",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Pending Review","Completed"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "0r9hrjl32e",
//       owner: "Administrator",
//       creation: "2026-01-30 19:29:43.354397",
//       modified: "2026-01-30 19:29:43.354397",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Completed","Open"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "17mkmk4srf",
//       owner: "Administrator",
//       creation: "2026-01-30 20:24:59.829250",
//       modified: "2026-01-30 20:24:59.829250",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Completed","Open"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "77l0l4gjtv",
//       owner: "Administrator",
//       creation: "2026-01-31 07:30:35.702400",
//       modified: "2026-01-31 07:30:35.702400",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Open","Working"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "78a1d66vn5",
//       owner: "Administrator",
//       creation: "2026-01-31 07:30:37.823610",
//       modified: "2026-01-31 07:30:37.823610",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Working","Pending Review"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "78tt37jvp0",
//       owner: "Administrator",
//       creation: "2026-01-31 07:30:39.763616",
//       modified: "2026-01-31 07:30:39.763616",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Pending Review","Completed"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "79jqb9tpb4",
//       owner: "Administrator",
//       creation: "2026-01-31 07:30:41.951112",
//       modified: "2026-01-31 07:30:41.951112",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Completed","Open"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "jc8icmdik8",
//       owner: "Administrator",
//       creation: "2026-01-30 20:01:20.860811",
//       modified: "2026-01-30 20:01:20.860811",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Open","Completed"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "jfa45gl3m6",
//       owner: "Administrator",
//       creation: "2026-01-30 20:01:30.603979",
//       modified: "2026-01-30 20:01:30.603979",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["type","Feature","Task"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "qnm67opqvc",
//       owner: "Administrator",
//       creation: "2026-01-30 20:13:54.255245",
//       modified: "2026-01-30 20:13:54.255245",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Completed","Open"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "r0fav3fa69",
//       owner: "Administrator",
//       creation: "2026-01-30 20:14:22.325425",
//       modified: "2026-01-30 20:14:22.325425",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Open","Working"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "r0re2jvsku",
//       owner: "Administrator",
//       creation: "2026-01-30 20:14:23.511688",
//       modified: "2026-01-30 20:14:23.511688",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Working","Open"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "r16rdid802",
//       owner: "Administrator",
//       creation: "2026-01-30 20:14:24.640679",
//       modified: "2026-01-30 20:14:24.640679",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Open","Pending Review"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "r1idj4sqrl",
//       owner: "Administrator",
//       creation: "2026-01-30 20:14:25.865305",
//       modified: "2026-01-30 20:14:25.865305",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Pending Review","Completed"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "su5vfl5t47",
//       owner: "Administrator",
//       creation: "2026-01-31 03:34:34.173947",
//       modified: "2026-01-31 03:34:34.173947",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Open","Completed"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//     {
//       name: "suhfb7i9a9",
//       owner: "Administrator",
//       creation: "2026-01-31 03:34:35.339382",
//       modified: "2026-01-31 03:34:35.339382",
//       modified_by: "Administrator",
//       docstatus: 0,
//       idx: 0,
//       ref_doctype: "Task",
//       custom_actual_doctype: null,
//       docname: "TASK-2026-00001",
//       custom_actual_document_name: null,
//       data: '{"added":[],"changed":[["status","Completed","Open"]],"data_import":null,"removed":[],"row_changed":[],"updater_reference":null}',
//     },
//   ];

  return (
    <div className="space-y-4">
      {versions.map((version) => (
        <div
          key={version.name}
          className="p-4 rounded-lg shadow-sm bg-slate-50 dark:bg-slate-800"
        >
          <div className="text-sm  mb-2">
           {version.modified_by}  Changes:
            <ul className="list-disc list-inside">
              {JSON.parse(version.data).changed.map((change, index) => (
                <li key={index}>
                  {change[0]}: "{change[1]}" → "{change[2]}"
                </li>
              ))}
            </ul>
          </div>
        </div>
      ))}
    </div>
  );
};

export default HistorySection;
