
from pydantic import BaseModel, Field
from typing import List, Optional, Literal


# ---------- Breakdown ----------
class GeneralResponse(BaseModel):
    message: str


        
class SuggestedTask(BaseModel):
    subject: str
    task_type: Literal["Task"]
    reason: str


# class SuggestedSubtask(BaseModel):
#     subject: str
#     description: str
#     task_type: Literal["SubTask"]
#     reason: str
class SuggestedSubtask(BaseModel):
    subject: str  # Short title of the subtask (one-line summary of the work)

    description: str  # Detailed explanation of what needs to be done in this subtask

    task_type: Literal["SubTask"]  # Defines the type of task object being created (useful if system supports multiple task types)

    reason: str  # Why this subtask was generated by the AI and how it contributes to the parent task

    priority: Literal["Low", "Medium", "High", "Urgent"]  # Importance level that determines urgency and scheduling

    complexity: Literal["Easy", "Medium", "Hard"]  # Estimated difficulty based on technical effort and required expertise

    estimated_effort: Optional[str]  # Human-readable time estimate like "2 hours", "1 day", or "3 days"

    estimated_hours: Optional[float]  # Numeric time estimate in hours for planning, reporting, and workload calculation

    execution_order: Optional[int]  # Suggested sequence order in which this subtask should be executed

    required_skills: List[str]  # Skills or technologies needed to complete the subtask (e.g., React, Python, SQL)

    suggested_role: Optional[str]  # Recommended role responsible for this task (e.g., Backend Developer, QA Engineer)

    depends_on: List[str]  # List of other subtasks that must be completed before this one can start

    deliverables: List[str]  # Tangible outputs expected when this task is completed (files, features, endpoints, etc.)

    acceptance_criteria: List[str]  # Conditions that must be satisfied for the task to be considered complete

    tags: List[str]  # Labels used for categorization, filtering, or grouping (e.g., backend, UI, optimization)

    risk_level: Literal["Low", "Medium", "High"]  # Indicates potential uncertainty, technical risk, or likelihood of delays

    automatable: bool  # Indicates whether this task could potentially be automated or assisted by AI/tools
class BreakdownResponse(BaseModel):
    message: str | None = None
    suggested_subtasks: List[SuggestedSubtask]


class CreateTasksResponse(BaseModel):
    message: str
    suggested_tasks: List[SuggestedTask]

# ---------- Improve ----------

class Improvement(BaseModel):
    original: str
    improved: str
    reason: str


class ImproveResponse(BaseModel):
    suggestions: List[Improvement]


# ---------- Risk ----------

class RiskItem(BaseModel):
    risk: str
    severity: Literal["Low", "Medium", "High"]
    mitigation: str


class RiskResponse(BaseModel):
    risks: List[RiskItem]


# ---------- Effort ----------

class EffortPhase(BaseModel):
    phase: str
    hours: str


class EffortEstimate(BaseModel):
    estimated_hours: str
    complexity: Literal["Low", "Medium", "High"]
    breakdown: List[EffortPhase]


class EffortResponse(BaseModel):
    estimate: EffortEstimate

